version: '3.9'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3307:3306
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: kamonsak_64114540025
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_PORT: ${DB_PORT}
volumes:
  db_data:
