version: '3.9'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - ./.env
    environment:
        MYSQL_USER: myuser
        MYSQL_PASSWORD: 1234
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: mydb
    ports:
      - 3307:3306
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: django
    command: sh -c "python manage.py runserver 0.0.0.0:80"
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASS=1234
volumes:
  db_data:
