# Generated by Django 4.2.7 on 2023-12-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="citizen_id",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
