# Generated by Django 4.2.4 on 2023-11-10 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="TemporaryUser",
            field=models.ManyToManyField(blank=True, to="interview.temporaryuser"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="role",
            name="TemporaryUser",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="interview.temporaryuser"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
