# Generated by Django 4.2.6 on 2024-02-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0002_alter_interviewlink_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewlink",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_round",
                to="interview.round",
            ),
        ),
    ]
