# Generated by Django 4.2.7 on 2023-12-13 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0002_alter_round_temporaryuser_alter_round_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="TemporaryUser",
            field=models.ManyToManyField(
                blank=True,
                related_name="rounds_participated",
                to="interview.temporaryuser",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="rounds_participated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
