# Generated by Django 4.2.7 on 2023-12-02 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0002_alter_user_citizen_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
