# Generated by Django 4.2.7 on 2024-02-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0003_user_first_name2_user_last_name2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule", name="end_date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="schedule", name="start_date", field=models.DateTimeField(),
        ),
    ]
