# Generated by Django 4.2.7 on 2023-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0003_alter_round_temporaryuser_alter_round_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="announcement", name="role",),
        migrations.RemoveField(model_name="announcement", name="round",),
        migrations.RemoveField(model_name="schedule", name="role",),
        migrations.RemoveField(model_name="schedule", name="round",),
        migrations.AddField(
            model_name="announcement",
            name="role",
            field=models.ManyToManyField(to="interview.role"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="round",
            field=models.ManyToManyField(to="interview.round"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="role",
            field=models.ManyToManyField(to="interview.role"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="round",
            field=models.ManyToManyField(to="interview.round"),
        ),
    ]
