# Generated by Django 4.2.6 on 2023-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0003_alter_major_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoretopic",
            name="score_detail",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
