# Generated by Django 4.2.7 on 2024-02-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0004_alter_schedule_end_date_alter_schedule_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="calendar_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
