# Generated by Django 4.2.6 on 2024-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0004_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="Shortnote",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
