# Generated by Django 4.2.6 on 2023-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "interview",
            "0004_remove_announcement_role_remove_announcement_round_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="doc_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
