# Generated by Django 4.2.6 on 2023-12-02 21:02

from django.db import migrations, models
import interview.models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0005_round_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(upload_to=interview.models.user_directory_path),
        ),
    ]
