# Generated by Django 4.2.6 on 2023-12-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0005_document_doc_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewlink",
            name="active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
