# Generated by Django 4.2.7 on 2024-01-04 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0006_interviewlink_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
