# Generated by Django 4.2.6 on 2023-12-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0006_round_active_alter_document_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewstatus",
            name="reg_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
