# Generated by Django 4.2.6 on 2024-01-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0007_alter_announcement_expire_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScorePattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_name", models.CharField(max_length=100)),
                ("main_pattern", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="scoretopic",
            name="pattern_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Score_pattern",
                to="interview.scorepattern",
            ),
        ),
    ]
