# Generated by Django 4.2.6 on 2024-01-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0008_scorepattern_alter_scoretopic_pattern_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roundscore",
            name="topic",
        ),
        migrations.AddField(
            model_name="roundscore",
            name="pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interview.scorepattern",
            ),
        ),
    ]
