# Generated by Django 4.2.6 on 2023-12-10 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0009_roundscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoretopic",
            name="round",
        ),
        migrations.DeleteModel(
            name="RoundScore",
        ),
    ]
