# Generated by Django 4.2.6 on 2024-01-15 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0009_remove_roundscore_topic_roundscore_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewlink",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_round",
                to="interview.round",
            ),
        ),
    ]
