# Generated by Django 4.2.6 on 2024-01-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0010_interviewlink_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewlink",
            name="interviewing",
            field=models.BooleanField(default=False),
        ),
    ]
