# Generated by Django 4.2.7 on 2023-12-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0011_roundscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="TemporaryUser",
            field=models.ManyToManyField(
                related_name="rounds_participated", to="interview.temporaryuser"
            ),
        ),
    ]
