# Generated by Django 4.2.7 on 2023-12-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0012_round_temporaryuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="citizen_id", field=models.CharField(max_length=13),
        ),
    ]
