# Generated by Django 4.2.6 on 2024-01-16 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0012_interviewnow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewnow",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
