# Generated by Django 4.2.7 on 2024-01-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_alter_interviewnow_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
    ]
