# Generated by Django 4.2.7 on 2024-01-18 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0015_alter_temporaryuser_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryuser",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 18, 10, 25, 34, 286643, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
