# Generated by Django 4.2.7 on 2024-01-18 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0016_alter_temporaryuser_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryuser",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
