# Generated by Django 4.2.7 on 2024-01-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0017_alter_temporaryuser_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="major",
            field=models.ManyToManyField(to="interview.major"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="major",
            field=models.ManyToManyField(to="interview.major"),
        ),
    ]
