# Generated by Django 4.2.7 on 2024-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0018_announcement_major_schedule_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="line_Token",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
