# Generated by Django 4.2.7 on 2024-01-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0019_round_line_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
