# Generated by Django 4.2.6 on 2024-01-19 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0020_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewlink",
            name="interviewing",
        ),
        migrations.AlterField(
            model_name="round",
            name="TemporaryUser",
            field=models.ManyToManyField(
                blank=True, related_name="round_temp_user", to="interview.temporaryuser"
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="round_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
