# Generated by Django 4.2.6 on 2024-01-30 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0021_remove_interviewlink_interviewing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="user",
        ),
        migrations.AddField(
            model_name="score",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_score",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_score",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
